### ISSUE TITLE
[Bug]: unsupported operand type(s) for |: 'type' and 'type'

### ISSUE THREAD

**Issue by jhll1124** [moesnow/March7thAssistant#274]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [x] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### March7thAssistant 版本 （或 Commit Id）

08c61ae
（2.2.0.3）
Latest

### 重现步骤

使用python运行程序

### 期望的结果是什么？

程序正常启动

### 实际的结果是什么？

Traceback (most recent call last):
  File "C:\Software\March7thAssistant\build.py", line 3, in <module>
    from tasks.weekly.universe import Universe
  File "C:\Software\March7thAssistant\tasks\weekly\universe.py", line 5, in <module>
    from tasks.base.base import Base
  File "C:\Software\March7thAssistant\tasks\base\base.py", line 3, in <module>
    from module.notification import notif
  File "C:\Software\March7thAssistant\module\notification\__init__.py", line 3, in <module>
    from module.notification.notification import Notification
  File "C:\Software\March7thAssistant\module\notification\notification.py", line 9, in <module>
    class Notification(metaclass=SingletonMeta):
  File "C:\Software\March7thAssistant\module\notification\notification.py", line 34, in Notification
    def _process_image(self, image: Optional[io.BytesIO | str | Image.Image]) -> Optional[io.BytesIO]:
TypeError: unsupported operand type(s) for |: 'type' and 'type'

### 补充说明（可选）

据查证，此问题是python 3.10版本新加入的功能所导致，如果在其以下版本运行会报错。建议兼容一下

**Comment by Rykzardz** [comment]
参考#182

**Comment by moesnow** [comment]
暂无计划，请升级到 Python 3.11.X
