### ISSUE TITLE
[Bug]: 打不开主程序。

### ISSUE THREAD

**Issue by hundouhuaer** [moesnow/March7thAssistant#293]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### March7thAssistant 版本 （或 Commit Id）

V2.3.0

### 重现步骤

打不开主程序
![屏幕截图 2024-06-08 212408](https://github.com/user-attachments/assets/65365acf-9135-4733-a2f5-e398e06df460)
Traceback (most recent call last):
  File "module\update\update_handler.py", line 32, in download_file
  File "tasks\base\download.py", line 18, in download_with_progress
Exception

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app.py", line 16, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "app\main_window.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "app\tools_interface.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "tasks\tool\__init__.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "tasks\tool\screenshot.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "module\ocr\__init__.py", line 69, in <module>
  File "module\ocr\__init__.py", line 63, in check_and_install
  File "module\ocr\__init__.py", line 55, in install_ocr
  File "module\update\update_handler.py", line 22, in run
  File "module\update\update_handler.py", line 37, in download_file
RuntimeError: input(): lost sys.stdin

### 期望的结果是什么？

1

### 实际的结果是什么？

1

### 日志记录

2024-07-18 02:04:54,432 | WARNING | OCR 路径不存在: .\3rdparty\PaddleOCR-json_v.1.3.1\PaddleOCR-json.exe
2024-07-18 02:04:54,437 | INFO | 开始下载: https://github.kotori.top/https://github.com/hiroi-sora/PaddleOCR-json/releases/download/v1.3.1/PaddleOCR-json_v.1.3.1.7z
2024-07-18 02:04:56,603 | ERROR | 下载失败: 
2024-07-18 02:05:05,397 | WARNING | OCR 路径不存在: .\3rdparty\PaddleOCR-json_v.1.3.1\PaddleOCR-json.exe
2024-07-18 02:05:05,403 | INFO | 开始下载: https://github.kotori.top/https://github.com/hiroi-sora/PaddleOCR-json/releases/download/v1.3.1/PaddleOCR-json_v.1.3.1.7z
2024-07-18 02:05:05,865 | ERROR | 下载失败: 
+-------------------------------------------------------------------------------------------------------------------+
|                                                   获取下载链接                                                    |
+-------------------------------------------------------------------------------------------------------------------+
2024-07-18 02:05:19,063 | INFO | 开始检测更新
2024-07-18 02:05:20,450 | INFO | 本地版本: v2.3.0
2024-07-18 02:05:20,451 | INFO | 远程版本: v2.3.0
2024-07-18 02:05:20,451 | INFO | 当前已是最新版本
2024-07-18 02:05:25,378 | WARNING | OCR 路径不存在: .\3rdparty\PaddleOCR-json_v.1.3.1\PaddleOCR-json.exe
2024-07-18 02:05:25,384 | INFO | 开始下载: https://github.kotori.top/https://github.com/hiroi-sora/PaddleOCR-json/releases/download/v1.3.1/PaddleOCR-json_v.1.3.1.7z
2024-07-18 02:05:25,837 | ERROR | 下载失败: 
2024-07-18 02:05:36,573 | WARNING | OCR 路径不存在: .\3rdparty\PaddleOCR-json_v.1.3.1\PaddleOCR-json.exe
2024-07-18 02:05:36,578 | INFO | 开始下载: https://github.kotori.top/https://github.com/hiroi-sora/PaddleOCR-json/releases/download/v1.3.1/PaddleOCR-json_v.1.3.1.7z
2024-07-18 02:05:37,045 | ERROR | 下载失败: 
+-------------------------------------------------------------------------------------------------------------------+
|                                                   获取下载链接                                                    |
+-------------------------------------------------------------------------------------------------------------------+
2024-07-18 02:06:51,835 | INFO | 开始检测更新
2024-07-18 02:06:56,700 | INFO | 本地版本: v2.3.0
2024-07-18 02:06:56,701 | INFO | 远程版本: v2.3.0
2024-07-18 02:06:56,701 | INFO | 当前已是最新版本

**Comment by niuhuan** [comment]
`RuntimeError: input(): lost sys.stdin`

当我们使用脚本或程序启动子进程，并且没有指定输入流的时候才会报此错误。

1. 请您尝试安装`Windows Terminal` ， 再次运行程序，观测是否仍有此错误
2. 如果仍然有错误，尝试手动打开一个管理员权限的 `Windows Termial` 页签，使用命令行执行此程序
