### ISSUE TITLE
[Bug]: 英文操作系统中，无法运行锄大地、差分宇宙/模拟宇宙等问题。

### ISSUE THREAD

**Issue by Abikita** [moesnow/March7thAssistant#411]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### March7thAssistant 版本 （或 Commit Id）

V2024.12.12

### 重现步骤

在Windows 10 Version 22H2 (OS Build 19045.4529) Education 版本系统的运行中，三月七小助手程序在识别主界面、设置界面等过程中可以正常运行，一旦涉及到战斗、跑图、进差分宇宙/模拟宇宙的时候就会闪退/完全卡死的问题。

### 期望的结果是什么？

正常运行

### 实际的结果是什么？

无法运行

### 日志记录

2024-12-17 00:46:14,489 | INFO | winotify 通知发送完成
+-------------------------------------------------------------------------------------------------------------------+
|                                                     开始运行                                                      |
+-------------------------------------------------------------------------------------------------------------------+
2024-12-17 00:48:58,788 | INFO | 游戏窗口已切换到前台
------------------------------------------------------- 完成 --------------------------------------------------------
+-------------------------------------------------------------------------------------------------------------------+
|                                                   准备模拟宇宙                                                    |
+-------------------------------------------------------------------------------------------------------------------+
2024-12-17 00:49:05,810 | INFO | 当前界面：主界面
2024-12-17 00:49:07,896 | INFO | 切换到：手机菜单
2024-12-17 00:49:12,519 | INFO | 切换到：星际和平指南-模拟宇宙
2024-12-17 00:49:21,008 | INFO | 切换到：差分宇宙-主界面
2024-12-17 00:49:23,915 | INFO | 当前界面：差分宇宙-主界面
2024-12-17 00:49:25,623 | INFO | 切换到：主界面
2024-12-17 00:49:29,004 | INFO | 切换到：差分宇宙-主界面
2024-12-17 00:49:29,506 | INFO | 开始模拟宇宙
2024-12-17 00:53:27,033 | ERROR | 模拟宇宙失败
2024-12-17 00:53:27,035 | ERROR | 模拟宇宙日志路径: .\3rdparty\Auto_Simulated_Universe\logs
2024-12-17 00:53:27,036 | INFO | 模拟宇宙未完成
+-------------------------------------------------------------------------------------------------------------------+
|                                                     开始运行                                                      |
+-------------------------------------------------------------------------------------------------------------------+
2024-12-17 01:02:39,425 | INFO | 游戏窗口已切换到前台
2024-12-17 01:02:45,744 | WARNING | 未识别出任何界面，请确保游戏画面干净，按ESC后重试
------------------------------------------------------- 完成 --------------------------------------------------------
+-------------------------------------------------------------------------------------------------------------------+
|                                                   准备模拟宇宙                                                    |
+-------------------------------------------------------------------------------------------------------------------+
2024-12-17 01:02:54,220 | INFO | 当前界面：手机菜单
2024-12-17 01:02:58,286 | INFO | 切换到：星际和平指南-模拟宇宙
2024-12-17 01:03:06,517 | INFO | 切换到：差分宇宙-主界面
2024-12-17 01:03:09,422 | INFO | 当前界面：差分宇宙-主界面
2024-12-17 01:03:11,117 | INFO | 切换到：主界面
2024-12-17 01:03:14,493 | INFO | 切换到：差分宇宙-主界面
2024-12-17 01:03:14,994 | INFO | 开始模拟宇宙
2024-12-17 01:30:28,753 | ERROR | 模拟宇宙失败
2024-12-17 01:30:28,756 | ERROR | 模拟宇宙日志路径: .\3rdparty\Auto_Simulated_Universe\logs
2024-12-17 01:30:28,770 | INFO | 模拟宇宙未完成
+-------------------------------------------------------------------------------------------------------------------+
|                                                     开始运行                                                      |
+-------------------------------------------------------------------------------------------------------------------+
2024-12-17 01:31:55,513 | INFO | 游戏窗口已切换到前台
------------------------------------------------------- 完成 --------------------------------------------------------
+-------------------------------------------------------------------------------------------------------------------+
|                                                   准备模拟宇宙                                                    |
+-------------------------------------------------------------------------------------------------------------------+
2024-12-17 01:32:01,908 | INFO | 当前界面：主界面
2024-12-17 01:32:03,597 | INFO | 切换到：手机菜单
2024-12-17 01:32:08,160 | INFO | 切换到：星际和平指南-模拟宇宙
2024-12-17 01:32:17,445 | INFO | 切换到：差分宇宙-主界面
2024-12-17 01:32:20,358 | INFO | 当前界面：差分宇宙-主界面
2024-12-17 01:32:22,080 | INFO | 切换到：主界面
2024-12-17 01:32:25,340 | INFO | 切换到：差分宇宙-主界面
2024-12-17 01:32:25,841 | INFO | 开始模拟宇宙
2024-12-17 01:36:49,491 | ERROR | 模拟宇宙失败
2024-12-17 01:36:49,493 | ERROR | 模拟宇宙日志路径: .\3rdparty\Auto_Simulated_Universe\logs
2024-12-17 01:36:49,495 | INFO | 模拟宇宙未完成
+-------------------------------------------------------------------------------------------------------------------+
|                                                     开始运行                                                      |
+-------------------------------------------------------------------------------------------------------------------+
2024-12-17 11:05:59,527 | INFO | 游戏窗口已切换到前台
------------------------------------------------------- 完成 --------------------------------------------------------
+-------------------------------------------------------------------------------------------------------------------+
|                                                   准备模拟宇宙                                                    |
+-------------------------------------------------------------------------------------------------------------------+
2024-12-17 11:06:05,212 | INFO | 当前界面：主界面
2024-12-17 11:06:07,617 | INFO | 切换到：手机菜单
2024-12-17 11:06:12,081 | INFO | 切换到：星际和平指南-模拟宇宙
2024-12-17 11:06:24,477 | INFO | 切换到：差分宇宙-主界面
2024-12-17 11:06:27,352 | INFO | 当前界面：差分宇宙-主界面
2024-12-17 11:06:28,970 | INFO | 切换到：主界面
2024-12-17 11:06:32,155 | INFO | 切换到：差分宇宙-主界面
2024-12-17 11:06:32,657 | INFO | 开始模拟宇宙
2024-12-17 11:07:21,037 | ERROR | 模拟宇宙失败
2024-12-17 11:07:21,039 | ERROR | 模拟宇宙日志路径: .\3rdparty\Auto_Simulated_Universe\logs
2024-12-17 11:07:21,040 | INFO | 模拟宇宙未完成
+-------------------------------------------------------------------------------------------------------------------+
|                                                     开始运行                                                      |
+-------------------------------------------------------------------------------------------------------------------+
2024-12-17 11:09:25,986 | INFO | 游戏窗口已切换到前台
------------------------------------------------------- 完成 --------------------------------------------------------
+-------------------------------------------------------------------------------------------------------------------+
|                                                    准备锄大地                                                     |
+-------------------------------------------------------------------------------------------------------------------+
2024-12-17 11:09:31,190 | INFO | 准备切换到队伍05
2024-12-17 11:09:35,186 | WARNING | 未识别出任何界面，请确保游戏画面干净，按ESC后重试
2024-12-17 11:09:41,854 | INFO | 当前界面：手机菜单
2024-12-17 11:09:44,905 | INFO | 切换到：队伍
2024-12-17 11:09:53,638 | INFO | 切换到队伍05成功
2024-12-17 11:09:53,639 | INFO | 开始锄大地
2024-12-17 11:09:53,987 | INFO | 当前界面：队伍
2024-12-17 11:09:55,559 | INFO | 切换到：主界面
2024-12-17 11:10:01,542 | ERROR | 锄大地失败
2024-12-17 11:10:01,543 | ERROR | 锄大地日志路径: .\3rdparty\Fhoe-Rail\logs
2024-12-17 11:10:01,544 | INFO | 锄大地未完成
2024-12-17 11:10:03,624 | INFO | winotify 通知发送完成
+-------------------------------------------------------------------------------------------------------------------+
|                                                     停止运行                                                      |
+-------------------------------------------------------------------------------------------------------------------+
2024-12-17 11:10:04,825 | INFO | 游戏终止：StarRail
------------------------------------------------------- 完成 --------------------------------------------------------
+-------------------------------------------------------------------------------------------------------------------+
|                                                   准备模拟宇宙                                                    |
+-------------------------------------------------------------------------------------------------------------------+
2024-12-17 12:55:06,190 | INFO | 当前界面：主界面
2024-12-17 12:55:07,718 | INFO | 切换到：手机菜单
2024-12-17 12:55:12,102 | INFO | 切换到：星际和平指南-模拟宇宙
2024-12-17 12:55:24,251 | INFO | 切换到：差分宇宙-主界面
2024-12-17 12:55:27,099 | INFO | 当前界面：差分宇宙-主界面
2024-12-17 12:55:28,656 | INFO | 切换到：主界面
2024-12-17 12:55:31,651 | INFO | 切换到：差分宇宙-主界面
2024-12-17 12:55:32,153 | INFO | 开始模拟宇宙
+-------------------------------------------------------------------------------------------------------------------+
|                                                     开始运行                                                      |
+-------------------------------------------------------------------------------------------------------------------+
2024-12-17 13:35:17,568 | INFO | 游戏窗口已切换到前台
2024-12-17 13:35:22,147 | WARNING | 未识别出任何界面，请确保游戏画面干净，按ESC后重试
------------------------------------------------------- 完成 --------------------------------------------------------
+-------------------------------------------------------------------------------------------------------------------+
|                                                    准备锄大地                                                     |
+-------------------------------------------------------------------------------------------------------------------+
2024-12-17 13:35:28,376 | INFO | 准备切换到队伍05
2024-12-17 13:35:31,735 | WARNING | 未识别出任何界面，请确保游戏画面干净，按ESC后重试
2024-12-17 13:35:37,993 | WARNING | 未识别出任何界面，请确保游戏画面干净，按ESC后重试
2024-12-17 13:35:44,248 | INFO | 当前界面：手机菜单
2024-12-17 13:35:46,398 | INFO | 切换到：队伍
2024-12-17 13:35:53,695 | INFO | 当前已经是队伍05了
2024-12-17 13:35:53,701 | INFO | 开始锄大地
2024-12-17 13:35:53,979 | INFO | 当前界面：队伍
2024-12-17 13:35:55,443 | INFO | 切换到：主界面
2024-12-17 13:36:00,421 | ERROR | 锄大地失败
2024-12-17 13:36:00,423 | ERROR | 锄大地日志路径: .\3rdparty\Fhoe-Rail\logs
2024-12-17 13:36:00,424 | INFO | 锄大地未完成
2024-12-17 13:36:02,101 | INFO | winotify 通知发送完成
+-------------------------------------------------------------------------------------------------------------------+
|                                                     停止运行                                                      |
+-------------------------------------------------------------------------------------------------------------------+
2024-12-17 13:36:03,174 | INFO | 游戏终止：StarRail
------------------------------------------------------- 完成 --------------------------------------------------------
2024-12-17 13:36:23,411 | INFO | 开始下载: https://github.kotori.top/https://github.com/linruowuyin/Fhoe-Rail/releases/download/2.7.04/Fhoe-Rail.zip
2024-12-17 13:36:24,755 | INFO | 下载完成: C:\March7thAssistant_v2024.12.12_full\March7thAssistant_v2024.12.12_full\temp\Fhoe-Rail.zip
2024-12-17 13:36:33,185 | INFO | 解压完成: C:\March7thAssistant_v2024.12.12_full\March7thAssistant_v2024.12.12_full\temp\Fhoe-Rail
+-------------------------------------------------------------------------------------------------------------------+
|                                                     开始运行                                                      |
+-------------------------------------------------------------------------------------------------------------------+
2024-12-17 13:36:59,469 | INFO | 游戏启动：C:\Star Rail Game\StarRail.exe
2024-12-17 13:37:09,471 | INFO | 游戏窗口已切换到前台
2024-12-17 13:37:50,883 | WARNING | 未识别出任何界面，请确保游戏画面干净，按ESC后重试
2024-12-17 13:37:56,474 | WARNING | 未识别出任何界面，请确保游戏画面干净，按ESC后重试
2024-12-17 13:38:02,134 | WARNING | 未识别出任何界面，请确保游戏画面干净，按ESC后重试
2024-12-17 13:38:07,758 | WARNING | 未识别出任何界面，请确保游戏画面干净，按ESC后重试
2024-12-17 13:38:13,373 | WARNING | 未识别出任何界面，请确保游戏画面干净，按ESC后重试
2024-12-17 13:38:18,971 | WARNING | 未识别出任何界面，请确保游戏画面干净，按ESC后重试
2024-12-17 13:38:24,094 | WARNING | 未识别出任何界面，请确保游戏画面干净，按ESC后重试
2024-12-17 13:38:30,390 | WARNING | 未识别出任何界面，请确保游戏画面干净，按ESC后重试
------------------------------------------------------- 完成 --------------------------------------------------------
+-------------------------------------------------------------------------------------------------------------------+
|                                                    准备锄大地                                                     |
+-------------------------------------------------------------------------------------------------------------------+
2024-12-17 13:38:37,011 | INFO | 准备切换到队伍05
2024-12-17 13:38:37,311 | INFO | 当前界面：主界面
2024-12-17 13:38:38,752 | INFO | 切换到：手机菜单
2024-12-17 13:38:41,251 | INFO | 切换到：队伍
2024-12-17 13:38:48,173 | INFO | 当前已经是队伍05了
2024-12-17 13:38:48,174 | INFO | 开始锄大地
2024-12-17 13:38:48,467 | INFO | 当前界面：队伍
2024-12-17 13:38:49,880 | INFO | 切换到：主界面
2024-12-17 13:38:53,129 | ERROR | 锄大地失败
2024-12-17 13:38:53,130 | ERROR | 锄大地日志路径: .\3rdparty\Fhoe-Rail\logs
2024-12-17 13:38:53,132 | INFO | 锄大地未完成
2024-12-17 13:38:54,715 | INFO | winotify 通知发送完成
+-------------------------------------------------------------------------------------------------------------------+
|                                                     停止运行                                                      |
+-------------------------------------------------------------------------------------------------------------------+
2024-12-17 13:38:55,851 | INFO | 游戏终止：StarRail
------------------------------------------------------- 完成 --------------------------------------------------------
+-------------------------------------------------------------------------------------------------------------------+
|                                                     开始运行                                                      |
+-------------------------------------------------------------------------------------------------------------------+
2024-12-17 13:50:03,507 | INFO | 游戏启动：C:\Star Rail Game\StarRail.exe
2024-12-17 13:50:13,936 | INFO | 游戏窗口已切换到前台
2024-12-17 13:50:49,841 | WARNING | 未识别出任何界面，请确保游戏画面干净，按ESC后重试
2024-12-17 13:50:55,392 | WARNING | 未识别出任何界面，请确保游戏画面干净，按ESC后重试
2024-12-17 13:51:01,367 | WARNING | 未识别出任何界面，请确保游戏画面干净，按ESC后重试
2024-12-17 13:51:07,540 | WARNING | 未识别出任何界面，请确保游戏画面干净，按ESC后重试
2024-12-17 13:51:13,639 | WARNING | 未识别出任何界面，请确保游戏画面干净，按ESC后重试
2024-12-17 13:51:19,370 | WARNING | 未识别出任何界面，请确保游戏画面干净，按ESC后重试
2024-12-17 13:51:24,875 | WARNING | 未识别出任何界面，请确保游戏画面干净，按ESC后重试
2024-12-17 13:51:30,125 | WARNING | 未识别出任何界面，请确保游戏画面干净，按ESC后重试
2024-12-17 13:51:35,656 | WARNING | 未识别出任何界面，请确保游戏画面干净，按ESC后重试
------------------------------------------------------- 完成 --------------------------------------------------------
+-------------------------------------------------------------------------------------------------------------------+
|                                                    准备锄大地                                                     |
+-------------------------------------------------------------------------------------------------------------------+
2024-12-17 13:51:41,803 | INFO | 准备切换到队伍05
2024-12-17 13:51:42,137 | INFO | 当前界面：手机菜单
2024-12-17 13:51:44,318 | INFO | 切换到：队伍
2024-12-17 13:51:51,602 | INFO | 当前已经是队伍05了
2024-12-17 13:51:51,604 | INFO | 开始锄大地
2024-12-17 13:51:51,944 | INFO | 当前界面：队伍
2024-12-17 13:51:53,440 | INFO | 切换到：主界面
2024-12-17 13:51:56,497 | ERROR | 锄大地失败
2024-12-17 13:51:56,499 | ERROR | 锄大地日志路径: .\3rdparty\Fhoe-Rail\logs
2024-12-17 13:51:56,499 | INFO | 锄大地未完成
2024-12-17 13:51:58,222 | INFO | winotify 通知发送完成
+-------------------------------------------------------------------------------------------------------------------+
|                                                     停止运行                                                      |
+-------------------------------------------------------------------------------------------------------------------+
2024-12-17 13:51:59,289 | INFO | 游戏终止：StarRail
------------------------------------------------------- 完成 --------------------------------------------------------
+-------------------------------------------------------------------------------------------------------------------+
|                                                   获取下载链接                                                    |
+-------------------------------------------------------------------------------------------------------------------+
2024-12-17 13:56:42,571 | INFO | 开始检测更新
2024-12-17 13:56:43,398 | INFO | 本地版本: v2024.12.12
2024-12-17 13:56:43,400 | INFO | 远程版本: v2024.12.12
2024-12-17 13:56:43,400 | INFO | 当前已是最新版本
2024-12-17 13:56:44,448 | INFO | 下载链接: https://github.com/moesnow/March7thAssistant/releases/download/v2024.12.12/March7thAssistant_v2024.12.12.7z
------------------------------------------------------- 完成 --------------------------------------------------------
+-------------------------------------------------------------------------------------------------------------------+
|                                                     终止进程                                                      |
+-------------------------------------------------------------------------------------------------------------------+
2024-12-17 13:56:52,913 | INFO | 开始终止进程...
2024-12-17 13:56:53,115 | INFO | 终止进程完成
------------------------------------------------------- 完成 --------------------------------------------------------
+-------------------------------------------------------------------------------------------------------------------+
|                                                       下载                                                        |
+-------------------------------------------------------------------------------------------------------------------+
2024-12-17 13:56:53,116 | INFO | 开始下载...
2024-12-17 13:56:57,043 | INFO | 下载完成: C:\March7thAssistant_v2024.12.12_full\March7thAssistant_v2024.12.12_full\temp\March7thAssistant_v2024.12.12.7z
------------------------------------------------------- 完成 --------------------------------------------------------
+-------------------------------------------------------------------------------------------------------------------+
|                                                       解压                                                        |
+-------------------------------------------------------------------------------------------------------------------+
2024-12-17 13:56:57,044 | INFO | 开始解压...
2024-12-17 13:57:04,518 | INFO | 解压完成: C:\March7thAssistant_v2024.12.12_full\March7thAssistant_v2024.12.12_full\temp\March7thAssistant_v2024.12.12
------------------------------------------------------- 完成 --------------------------------------------------------
+-------------------------------------------------------------------------------------------------------------------+
|                                                       覆盖                                                        |
+-------------------------------------------------------------------------------------------------------------------+
2024-12-17 13:57:04,520 | INFO | 开始覆盖...
2024-12-17 13:57:18,647 | INFO | 覆盖完成: C:\March7thAssistant_v2024.12.12_full\March7thAssistant_v2024.12.12_full
------------------------------------------------------- 完成 --------------------------------------------------------
+-------------------------------------------------------------------------------------------------------------------+
|                                                       清理                                                        |
+-------------------------------------------------------------------------------------------------------------------+
2024-12-17 13:57:18,649 | INFO | 开始清理...
2024-12-17 13:57:18,657 | INFO | 清理完成: C:\March7thAssistant_v2024.12.12_full\March7thAssistant_v2024.12.12_full\temp\March7thAssistant_v2024.12.12.7z
2024-12-17 13:57:19,128 | INFO | 清理完成: C:\March7thAssistant_v2024.12.12_full\March7thAssistant_v2024.12.12_full\temp\March7thAssistant_v2024.12.12
------------------------------------------------------- 完成 --------------------------------------------------------
+-------------------------------------------------------------------------------------------------------------------+
|                                                    准备锄大地                                                     |
+-------------------------------------------------------------------------------------------------------------------+
2024-12-17 14:01:27,599 | INFO | 准备切换到队伍05
2024-12-17 14:01:27,894 | INFO | 当前界面：主界面
2024-12-17 14:01:29,351 | INFO | 切换到：手机菜单
2024-12-17 14:01:31,980 | INFO | 切换到：队伍
2024-12-17 14:01:39,100 | INFO | 当前已经是队伍05了
2024-12-17 14:01:39,102 | INFO | 开始锄大地
2024-12-17 14:01:39,403 | INFO | 当前界面：队伍
2024-12-17 14:01:40,873 | INFO | 切换到：主界面
2024-12-17 14:01:43,157 | ERROR | 锄大地失败
2024-12-17 14:01:43,159 | ERROR | 锄大地日志路径: .\3rdparty\Fhoe-Rail\logs
2024-12-17 14:01:43,172 | INFO | 锄大地未完成
2024-12-17 14:01:44,915 | INFO | winotify 通知发送完成
+-------------------------------------------------------------------------------------------------------------------+
|                                                     停止运行                                                      |
+-------------------------------------------------------------------------------------------------------------------+
2024-12-17 14:01:45,724 | INFO | 游戏终止：StarRail
------------------------------------------------------- 完成 --------------------------------------------------------

**Comment by Abikita** [comment]
提示的.\3rdparty\Fhoe-Rail\logs路径内，logs是空的

**Comment by Abikita** [comment]
锄大地功能点击原版运行后，回一闪而过这个界面
<img width="656" alt="微信图片_20241217154718" src="https://github.com/user-attachments/assets/8efd071f-0c7e-4089-90e4-facdf836ef3d" />

内容：
Error: [WinError 2] The system cannot find the file specified: 'map'
Error: [WinError 2] The system cannot find the file specified: 'map'
Traceback (most recent call last):
  File "fhoe.py", line 348, in <module>
  File "fhoe.py", line 100, in print_info
  File "loguru\_logger.py", line 2078, in info
  File "loguru\_logger.py", line 2063, in _log
  File "utils\log.py", line 40, in update_extra
  File "utils\log.py", line 28, in get_ver
TypeError: cannot unpack non-iterable NoneType object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fhoe.py", line 358, in <module>
  File "loguru\_logger.py", line 2090, in error
  File "loguru\_logger.py", line 2063, in _log
  File "utils\log.py", line 40, in update_extra
  File "utils\log.py", line 28, in get_ver
TypeError: cannot unpack non-iterable NoneType object
[PYI-3620:ERROR] Failed to execute script 'fhoe' due to unhandled exception!

**Comment by moesnow** [comment]
`Error: [WinError 2] The system cannot find the file specified: 'map'`

没看懂和英文操作系统有什么关系，这不是很明显提示你丢失 `map` 文件夹了吗。

重新下载 [March7thAssistant_v2024.12.12_full.zip](https://github.com/moesnow/March7thAssistant/releases/download/v2024.12.12/March7thAssistant_v2024.12.12_full.zip) 试试

**Comment by Abikita** [comment]
> `Error: [WinError 2] The system cannot find the file specified: 'map'`
> 
> 没看懂和英文操作系统有什么关系，这不是很明显提示你丢失 `map` 文件夹了吗。
> 
> 重新下载 [March7thAssistant_v2024.12.12_full.zip](https://github.com/moesnow/March7thAssistant/releases/download/v2024.12.12/March7thAssistant_v2024.12.12_full.zip) 试试，或者尝试 `主页` → `锄大地` → `更新锄大地`

仍然无法解决，换了一台国人的电脑发现就没这方面的问题，我把这电脑重装一下吧，待会再看看

**Comment by Abikita** [comment]
> `Error: [WinError 2] The system cannot find the file specified: 'map'`
> 
> 没看懂和英文操作系统有什么关系，这不是很明显提示你丢失 `map` 文件夹了吗。
> 
> 重新下载 [March7thAssistant_v2024.12.12_full.zip](https://github.com/moesnow/March7thAssistant/releases/download/v2024.12.12/March7thAssistant_v2024.12.12_full.zip) 试试，或者尝试 `主页` → `锄大地` → `更新锄大地`

重装系统之后就解决了，我觉得可能是我们实验室的系统问题，有一个无法卸载的防火墙和Trend Micro杀毒软件，应该是在运行的时候被阻挡了，而且没有白名单，重装系统之后把这俩去掉就能用了
